import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";

import { Toaster } from "react-hot-toast";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Pulldown } from "./components/Pulldown";
import { Suspense } from "react";
import { LoadingIcon } from "./components/Icons";
import { CheckoutProvider } from "@/lib/contexts/use-checkout-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["200", "400", "500", "600", "700", "800"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Suspense fallback={<Loadingpage />}>
        <body
          // style={{ overflowY: "auto" }}
          className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased relative `}
        >
          <Toaster position="top-center" />
          <CheckoutProvider>
            <Pulldown />
            <Header isDropdownOpen={true} />
            {/* <Loadingpage /> */}
            <div id="modal-root" />
            {children}
            <Footer />
          </CheckoutProvider>
        </body>
      </Suspense>
    </html>
  );
}

function Loadingpage() {
  return (
    <div className="w-full  h-150 flex items-center justify-center">
      {/* Loading search params… */}
      <div className="w-20 h-20  animate-spin flex justify-center items-center">
        <LoadingIcon size={120} />
      </div>
    </div>
  );
}

// function Pulldown() {
//   return (
//     <div className="w-full  h-8  justify-center bg-gray-darker flex items-center px-4">
//       <div className="no-select flex gap-[18px] justify-center items-center">
//         <ChevronDown />
//         <span className="text-white font-medium uppercase text-center text-sm ">
//           Shipping & Free Returns
//         </span>
//         <ChevronDown />
//       </div>
//     </div>
//   );
// }
