import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { ChevronDown } from "./components/Icons";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["200", "400", "500", "600", "700", "800"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased w-screen`}
      >
        <Pulldown />
        {children}
      </body>
    </html>
  );
}

function Pulldown() {
  return (
    <div className="w-full  h-8  justify-center bg-gray-darker flex items-center px-4">
      <div className="no-select flex gap-[18px] justify-center items-center">
        <ChevronDown />
        <span className="text-white font-medium uppercase text-center text-sm ">
          Shipping & Free Returns
        </span>
        <ChevronDown />
      </div>
    </div>
  );
}
